import Header from "./Header"
import Main from "./Main"
import {Details} from "./Details"
import {TotalDetails} from "./Details"
import RegTypes from "./RegTypes"
import RegForm from "./RegForm"
import Workshop from "./Workshop"
import Home from "./Home"
import {RegType} from "./Headings"
import { WorkshopNot } from "./Notifications"
export {Header, Main, Details, RegTypes, RegForm, Workshop, Home, RegType, WorkshopNot, TotalDetails }